### ISSUE TITLE
Add Drupal Hyderabad logo to the repo

### ISSUE THREAD

**Issue by shashikanth171** [drupalin/OpenDesign#1]
## Goal: 
Add Drupal Hyderabad logo to the repo

## Info: 
Branding for the Drupal Hyderabad community

## Style Information: 
Upload the current logo

## Deadline: 
ASAP

## Tag: 
[Drupal Hyderabad, Logo]

**Comment by bhavabhuthi** [comment]
Created by @bhavabhuthi and @thekishanraval 

![drupal hyderabad logo - camp theme](https://cloud.githubusercontent.com/assets/26624774/25562437/ec26a6dc-2da3-11e7-9550-012d94e5e08b.png)
[Drupal Hyderabad logo - Camp theme.zip](https://github.com/drupalhyderabad/OpenDesign/files/966604/Drupal.Hyderabad.logo.-.Camp.theme.zip)

**Comment by ranjithrajv** [comment]
Thanks
