### ISSUE TITLE
Drupal Hyderabad Webinars

### ISSUE THREAD

**Issue by shashikanth171** [drupalin/OpenDesign#2]
## Goal: 
Event Promotion 

## Info: 
Branding

## Style Information: 
With a gentle touch of Hyderabad

## Deadline: 
April 27, 2017

## Tag: 
[Drupal Hyderbad, Webinars, Logo]

**Comment by bhavabhuthi** [comment]
created by @bhavabhuthi and @thekishanraval

![drupal hyderabad webinars logo - camp theme](https://cloud.githubusercontent.com/assets/26624774/25562538/b4583de0-2da5-11e7-86b9-ae81b3ef625d.png)
[Drupal Hyderabad Webinars logo - Camp theme.zip](https://github.com/drupalhyderabad/OpenDesign/files/966611/Drupal.Hyderabad.Webinars.logo.-.Camp.theme.zip)

**Comment by sairamraavi** [comment]
its perfect
