### ISSUE TITLE
Drupal Monthly meetup #5

### ISSUE THREAD

**Issue by sairamraavi** [drupalin/OpenDesign#5]
## Goal: 
Drupal monthly meet up poster

## Info: 
With azri logo and azri platform along with drupal hyderabad meetup logo 

## Style Information: 
Go with Webinar style and DrupalCamp Hyderabad style

## Deadline: 
May 9th

## Tag: 
DrupalHyderabad, Drupal meet-up's, Azri meetup

**Comment by bhavabhuthi** [comment]
Done by @bhavabhuthi and @thekishanraval

[Drupal Hyderabad - 13th may Meetup.zip](https://github.com/drupalhyderabad/OpenDesign/files/987885/Drupal.Hyderabad.-.13th.may.Meetup.zip)

![drupal hyderabad - 13th may meetup](https://cloud.githubusercontent.com/assets/26624774/25870421/9c236c80-3521-11e7-8503-e922bb2f21de.png)

![drupal hyderabad - 13th may meetup fb](https://cloud.githubusercontent.com/assets/26624774/25870418/9c1783e8-3521-11e7-9c2d-5184e7a16598.png)

![drupal hyderabad - 13th may meetup hd](https://cloud.githubusercontent.com/assets/26624774/25870419/9c17aeb8-3521-11e7-96e3-50a30ff10ef5.png)

![drupal hyderabad - 13th may meetup twitter](https://cloud.githubusercontent.com/assets/26624774/25870420/9c19db98-3521-11e7-9042-0e2101958a27.png)
